# Generated by Django 5.0.2 on 2024-04-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="active",
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
