# Generated by Django 5.0.2 on 2024-04-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_owner_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="outlet",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
