# Generated by Django 5.0.2 on 2024-04-23 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_owner_outlet"),
    ]

    operations = [
        migrations.CreateModel(
            name="otp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outlet_id",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                (
                    "otp",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                (
                    "owner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="login.owner"
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
