# Generated by Django 5.0.2 on 2024-04-23 06:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0004_otp"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="otp",
            new_name="otp_table",
        ),
    ]
