# Generated by Django 5.0.2 on 2024-04-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0005_rename_otp_otp_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="shift_end",
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="owner",
            name="shift_start",
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
