# Generated by Django 5.0.2 on 2024-04-04 06:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("good_recieve", "0014_orderedmed_accept"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pr_id", models.BigIntegerField(blank=True, default=None, null=True)),
                ("po_id", models.BigIntegerField(blank=True, default=None, null=True)),
                (
                    "purchase_id",
                    models.BigIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "outlet_shortcode",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="good_recieve.companylist",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
