# Generated by Django 5.0.2 on 2024-04-04 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_recieve", "0014_orderedmed_accept"),
        ("inventory", "0003_inventorylist_outlet_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryMed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "med_name",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "quantity",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "buying_price",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "selling_price",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "total",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "vat_percentage",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "total_vat",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="good_recieve.companylist",
                    ),
                ),
                (
                    "inventory_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventorylist",
                    ),
                ),
                (
                    "req_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="good_recieve.orderlist",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
