# Generated by Django 5.0.2 on 2024-04-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_inventorymed"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymed",
            name="quantity_total",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
