# Generated by Django 5.0.2 on 2024-04-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_inventorymed_quantity_total"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventorymed",
            old_name="quantity_total",
            new_name="quantity_stock",
        ),
        migrations.AddField(
            model_name="inventorymed",
            name="quantity_sold",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
