# Generated by Django 5.0.2 on 2024-04-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0006_rename_quantity_total_inventorymed_quantity_stock_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymed",
            name="status",
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
