# Generated by Django 5.0.2 on 2024-04-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_inventorymed_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymed",
            name="total_vat_mrp",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="inventorymed",
            name="total_vat",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
