# Generated by Django 5.0.2 on 2024-04-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_inventorymed_total_vat_mrp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymed",
            name="expired_date",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
