# Generated by Django 5.0.2 on 2024-04-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_inventorymed_expired_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorylist",
            name="purchase_id",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
