# Generated by Django 5.0.2 on 2024-04-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_alter_inventorylist_purchase_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorylist",
            name="voucher",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
