# Generated by Django 5.0.2 on 2024-05-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_inventorymed_generic_inventorymed_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorylist",
            name="receive_by",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
