# Generated by Django 5.0.2 on 2024-05-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_stocktransferlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktransferlist",
            name="outlet_id",
        ),
        migrations.RemoveField(
            model_name="stocktransferlist",
            name="req_id",
        ),
        migrations.AddField(
            model_name="stocktransferlist",
            name="to_outlet_id",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
