# Generated by Django 5.0.2 on 2024-05-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_remove_stocktransferlist_outlet_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransferlist",
            name="from_outlet_id",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
