# Generated by Django 5.0.2 on 2024-05-09 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_stocktransferlist_from_outlet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransferlist",
            name="inventory_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.inventorylist",
            ),
            preserve_default=False,
        ),
    ]
