# Generated by Django 5.0.2 on 2024-03-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_recieve", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companylist",
            name="companyName",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
