# Generated by Django 5.0.2 on 2024-03-18 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_recieve", "0002_alter_companylist_companyname"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "med_name",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="good_recieve.companylist",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
