# Generated by Django 5.0.2 on 2024-03-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_recieve", "0003_medlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="medlist",
            name="buying_price",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="medlist",
            name="selling_price",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
