# Generated by Django 5.0.2 on 2024-03-25 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_recieve", "0006_orderlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlist",
            name="create_date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
