# Generated by Django 5.0.2 on 2024-03-25 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_recieve", "0008_orderlist_po_date_orderlist_pr_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlist",
            name="outlet_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="good_recieve.pharmacylist",
            ),
        ),
    ]
