# Generated by Django 5.0.2 on 2024-03-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_recieve", "0009_orderlist_outlet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlist",
            name="outlet_shortcode",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
