# Generated by Django 5.0.2 on 2024-03-25 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_recieve", "0010_orderlist_outlet_shortcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlist",
            name="outlet_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="good_recieve.pharmacylist",
            ),
        ),
    ]
