# Generated by Django 5.0.2 on 2024-03-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_recieve", "0011_alter_orderlist_outlet_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlist",
            name="outlet_id",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
