# Generated by Django 5.0.2 on 2024-04-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_recieve", "0014_orderedmed_accept"),
    ]

    operations = [
        migrations.AddField(
            model_name="companylist",
            name="shortCode",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
