# Generated by Django 5.0.2 on 2024-05-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_recieve", "0015_companylist_shortcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedmed",
            name="generic",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="orderedmed",
            name="unit",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
