# Generated by Django 5.0.2 on 2024-05-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_recieve", "0016_orderedmed_generic_orderedmed_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="med_unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
