# Generated by Django 5.0.2 on 2024-05-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_recieve", "0018_orderlist_order_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="generic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
