# Generated by Django 5.0.2 on 2024-05-13 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("good_recieve", "0019_generic"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="generic",
            new_name="generic_list",
        ),
    ]
