# Generated by Django 5.0.2 on 2024-05-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("good_recieve", "0020_rename_generic_generic_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlist",
            name="pr_date",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="orderlist",
            name="pr_id",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
