# Generated by Django 5.0.2 on 2024-04-28 10:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("login", "0005_rename_otp_otp_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "register_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="login.owner"
                    ),
                ),
            ],
        ),
    ]
